INSERT INTO PALAVRAS(201, 'Selmini', 4);

INSERT INTO PALAVRAS(202, 'Humberto', 4);

INSERT INTO PALAVRAS(203, 'Flávio', 4);

INSERT INTO PALAVRAS(204, 'Vince Vader', 4);

INSERT INTO PALAVRAS(205, 'Life Lab', 4);