var bancoPalavras = [
    palavras1 = [
        'casa',
        'cerveja',
        'refrigerante',
        'pastel',
        'bola',
        'bicicleta',
        'skate',
        'carro',
        'moto',
        'ônibus',
        'violão',
        'celular',
        'whatsapp',
        'fone de ouvido',
        'cama',
        'avião',
        'gato',
        'cachorro',
        'cavalo',
        'televisão',
        'água',
        'sol',
        'praia',
        'mesa',
        'cadeira',
        'prato',
        'garfo',
        'faca',
        'caneta',
        'lápis',
        'borracha',
        'vassoura',
        'boca',
        'olho',
        'nariz',
        'ouvido',
        'tênis',
        'garrafa',
        'castelo',
        'rei',
        'rainha',
        'fada',
        'sereia',
        'pirata',
        'policial',
        'vaca',
        'galinha',
        'ovo',
        'abelha',
        'mel',
        'milho',
        'agenda',
        'pipoca',
        'borboleta',
        'linha',
        'cantor',
        'feijão',
        'arroz',
        'café',
        'peixe',
        'banana',
        'maçã',
        'abacaxi',
        'melancia',
        'vestido',
        'colar',
        'colher',
        'uva',
        'chá',
        'árvore',
        'rato',
        'relógio',
        'chave',
        'pomba',
        'macaco',
        'planta',
        'papel',
        'chiclete',
        'céu',
        'mar',
        'flor',
        'folha'],
    palavras2 = [
        'sunga',
        'batata',
        'boia',
        'bexiga',
        'baú',
        'azeite',
        'açúcar',
        'andar',
        'cinema',
        'caixa',
        'sanduíche',
        'chinelo',
        'mochila',
        'chorar',
        'bala',
        'bruxa',
        'canudo',
        'cogumelo',
        'lixo',
        'boneca',
        'buzina',
        'baleia',
        'nadar',
        'dormir',
        'lua',
        'leoa',
        'lavar',
        'luva',
        'lixa',
        'leite',
        'limonada',
        'lobo',
        'urso',
        'porta',
        'sorvete',
        'caderno',
        'carteira',
        'circo',
        'elevador',
        'princesa',
        'gigante',
        'gnomo',
        'tesouro',
        'professor',
        'caçador',
        'papagaio',
        'unicórnio',
        'fantasma',
        'vampiro',
        'chocolate',
        'tubarão',
        'livro',
        'estojo',
        'lontra',
        'museu',
        'navio',
        'cabra',
        'porco',
        'bolo',
        'alho',
        'cruz',
        'estátua',
        'calendário',
        'tucano',
        'caju',
        'remédio',
        'queijo',
        'brigadeiro',
        'mosca',
        'vírus',
        'calça',
        'bota',
        'capivara',
        'baralho',
        'presente',
        'anão',
        'molho',
        'aplicativo',
        'letra',
        'tomada',
        'filme',
        'série',
        'videogame',
        'novela'],
    palavras3 = [
        'ler',
        'lagartixa',
        'vidro',
        'dançar',
        'estudar',
        'brincar',
        'amar',
        'descobrir',
        'futuro',
        'julgar',
        'digitar',
        'escutar',
        'perder',
        'guiar',
        'conduzir',
        'paciência',
        'apostar',
        'passar',
        'missão',
        'açougue',
        'esquecer',
        'voltar',
        'pulmão',
        'sozinho',
        'financiar',
        'balcão',
        'lava',
        'declaração',
        'piscina',
        'louco',
        'soldado',
        'pista',
        'dinheiro',
        'segredo',
        'fé',
        'ré',
        'contar',
        'infarto',
        'ajudar',
        'dragão',
        'cavaleiro',
        'feiticeiro',
        'ciclope',
        'muralha',
        'medalhão',
        'duende',
        'fazendeiro',
        'índio',
        'imperador',
        'assombração',
        'centauro',
        'zumbi',
        'golfinho',
        'agulha',
        'lobisomem',
        'múmia',
        'faraó',
        'hambúrger',
        'jaca',
        'feijoada',
        'baile',
        'paisagem',
        'salsicha',
        'caçoar',
        'carregador',
        'umidificador',
        'pavão',
        'corvo',
        'chalé',
        'adega',
        'vinícola',
        'algoritmo',
        'úbere',
        'logaritmo',
        'aspargo',
        'cachimbo',
        'esfincter',
        'promontório',
        'ambrosia',
        'refúgio',
        'pochete',
        'violoncelo',
        'moinho',
        'moela',
        'templário',
        'babuíno',
        'cucuia'],
    palavras4 = [
        'selmini',
        'humberto',
        'flávio',
        'vince vader',
        'life lab',
        'gamelab',
        'espm júnior',
        'marketing',
        'jacarito',
        'war vikings',
        'smooh',
        'andré',
        'surjan',
        'surian',
        'sandra',
        'rafa',
        'administração',
        'ciências sociais e do consumo',
        'cinema e audiovisual',
        'design',
        'design de moda',
        'jornalismo',
        'publicidade e propaganda',
        'relações internacionais',
        'sistemas de informação',
        'arenas',
        'atlética',
        'tv pixel',
        'grupo tangerina',
        'espm social',
        'overbite',
        'centro acadêmico 4 de dezembro (CA4D)',
        'diretório acadêmico guerreiro ramos (DAGR)',
        'quadra',
        'ludoteca',
        'biblioteca',
        'sala ps4',
        'sql',
        'phaser',
        'filósofo',
        'jesus',
        'ovelha',
        'terraço',
        'churrasco',
        'vinho barolo',
        'bolo bruto',
        'among us',
        'tururu',
        'jack black',
        'ameno',
        'mlp',
        'jogo akinator',
        'sleepover',
        'cervejada'
        ]
]

var semPalavras = false

function sortearPalavra() {
    if (round < 1 || round > 4) {
        return 'round bugado!'
    }
    var palavras = bancoPalavras[round - 1]
    var i = Math.floor(Math.random() * palavras.length);
    var palavra = palavras[i];
    palavras.splice(i, 1);

    if (palavras.length == 0) {
        //acaba o round
        $("#avisos").text("As palavras deste round acabaram!")
        semPalavras = true
        return ""
    }
    return palavra;
}

function mostrarPalavra() {
    $("#palavra").text(sortearPalavra)
}

function validarPalavra() {
    if(semPalavras){
        return
    }
    if ( $("#palavra").text() == $("#palpite").val()) {
        $("#avisos").text("Correto!")
        pontos++
        $("#pontos").text(pontos)
        mostrarPalavra()

    }
    else {
        $("#avisos").text("Falso!")
        $("#pontos").text(pontos)
    }

}