

lista "LISTAS" "dificuldade 1"

INSERT INTO PALAVRAS(1, 'casa', 1);

INSERT INTO PALAVRAS(2, 'cerveja', 1);

INSERT INTO PALAVRAS(3, 'refrigerante', 1);

INSERT INTO PALAVRAS(4, 'pastel', 1);

INSERT INTO PALAVRAS(5, 'bola', 1);

INSERT INTO PALAVRAS(6, 'bicicleta', 1);

INSERT INTO PALAVRAS(7, 'skate', 1);

INSERT INTO PALAVRAS(8, 'carro', 1);

INSERT INTO PALAVRAS(9, 'moto', 1);

INSERT INTO PALAVRAS(10, 'onibus', 1);

INSERT INTO PALAVRAS(11, 'violão', 1);

INSERT INTO PALAVRAS(12, 'celular', 1);

INSERT INTO PALAVRAS(13, 'whatsapp', 1);

INSERT INTO PALAVRAS(14, 'fone de ouvido', 1);

INSERT INTO PALAVRAS(15, 'cama', 1);

INSERT INTO PALAVRAS(16, 'avião', 1);

INSERT INTO PALAVRAS(17, 'gato', 1);

INSERT INTO PALAVRAS(18, 'cachorro', 1);

INSERT INTO PALAVRAS(19, 'cavalo', 1);

INSERT INTO PALAVRAS(20, 'televisão', 1);

INSERT INTO PALAVRAS(21, 'água', 1);

INSERT INTO PALAVRAS(22, 'sol', 1);

INSERT INTO PALAVRAS(23, 'praia', 1);

INSERT INTO PALAVRAS(24, 'mesa', 1);

INSERT INTO PALAVRAS(25, 'cadeira', 1);

INSERT INTO PALAVRAS(26, 'prato', 1);

INSERT INTO PALAVRAS(27, 'garfo', 1);

INSERT INTO PALAVRAS(28, 'faca', 1);

INSERT INTO PALAVRAS(29, 'caneta', 1);

INSERT INTO PALAVRAS(30, 'lápis', 1);

INSERT INTO PALAVRAS(31, 'borracha', 1);

INSERT INTO PALAVRAS(32, 'vassoura', 1);

INSERT INTO PALAVRAS(33, 'boca', 1);

INSERT INTO PALAVRAS(34, 'olho', 1);

INSERT INTO PALAVRAS(35, 'nariz', 1);

INSERT INTO PALAVRAS(36, 'ouvido', 1);

INSERT INTO PALAVRAS(1, 'tênis', 1);

INSERT INTO PALAVRAS(1, 'Selmini', 1);

INSERT INTO PALAVRAS(1, 'Humberto', 1);

INSERT INTO PALAVRAS(1, 'Flávio', 1);